### ISSUE TITLE
Code breaking without throwing any failure when trying to work with firestore emulator 

### ISSUE THREAD

**Issue by stinkidog** [googleapis/google-cloud-dotnet#5862]
I've been searching everywhere for direction with this, but not had the fortune of finding any help. I have a project which contains the gcp emulator (including firestore, pubsub, realtime db, cloud functions etc), and a .NET 5 service, both running in their own separate docker containers.

I want to be able to push to the firestore in the emulator from my .NET service using this library, but I'm coming across some strange behavior when debugging.

An endpoint receives a request, and triggers a service to handle the processing. The first thing the service method does is to detect for a running emulator as per the following:

`FirestoreDb db = new FirestoreDbBuilder
            {
                ProjectId = "MyProjectId",
                EmulatorDetection = EmulatorDetection.EmulatorOrProduction
            }.Build();`

This is taken from the one article I managed to find. The problem is, that when I put a breakpoint on this lane, it breaks out of the method, returns back to the controller, and returns a 200 status. It doesn't fail, but it gives no error, and skips the entire logic within the body of the method.

The article also states the following: 

> To connect to the Firestore Emulator, you need to:

> Connect to the emulator endpoint
> Use ChannelCredentials.Insecure as the channel credentials
> Specify an "Authorization: Bearer owner" header on each request

Which makes sense, but there are no examples so I feel I'm shooting mostly blind. I did add the environment variable to my .NET container with the path to the json credentials file (also on the .NET container), but that did not solve anything.

**Comment by jskeet** [comment]
I find it hard to understand how a method can return abruptly but without throwing an exception... I normally find that when something looks like that, there's really an exception being swallowed somewhere.

Please could you provide a complete example? A console application (which could still run in your container of course) would be ideal as it would make it simpler to reproduce completely than a service. If the console app works but the service still fails, that would be interesting information in itself.

Additionally, does your service work when you *don't* use the emulator?

**Comment by stinkidog** [comment]
Thank for the reply Jon. So what I've done to play with this, is to create a .NET 5 console app - absolutely nothing special about it.
I've added the google.cloud.firestore nuget package, and added the following DummyClass:

    public class DummyService
     {
        public async Task PushToFirestoreEmulator(string someData)
        {
            FirestoreDb db = new FirestoreDbBuilder
            {
                ProjectId = "MyProjectId",
                EmulatorDetection = EmulatorDetection.EmulatorOrProduction
            }.Build();
            Console.WriteLine("We never get here");
        }
    }
    
My main file then simply makes a call to this class:
   
    class Program
    {
        static async Task Main(string[] args)
        {
            DummyService service = new DummyService();
            await service.PushToFirestoreEmulator("Hello emulator");
            Console.WriteLine("Hello World!");
        }
    }
    
It is Dockerized by using vs built in functionality, the Dockerfile looks as so:
    
    FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim AS base
    WORKDIR /app
    FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
    WORKDIR /src
    COPY ["TestConsole/TestConsole.csproj", "TestConsole/"]
    RUN dotnet restore "TestConsole/TestConsole.csproj"
    COPY . .
    WORKDIR "/src/TestConsole"
    RUN dotnet build "TestConsole.csproj" -c Release -o /app/build
    FROM build AS publish
    RUN dotnet publish "TestConsole.csproj" -c Release -o /app/publish
    FROM base AS final
    WORKDIR /app
    COPY --from=publish /app/publish .
    ENTRYPOINT ["dotnet", "TestConsole.dll"]

I've added the .json file for the credentials to the project, and set the environment variable in my docker-compose file as the following, but this won't be able to be reproduced by yourself as it is linked to our own service account on our project. I'm fairly new to GCP so please advise if there is a better way I can share an example. 

Anyway, it was failing with those credentials, but then once added, created a new error which is now a DllNotFoundException for a library 'libdl' - which is a completely separate error to what I'm seeing in my service. It could be that this is the masked error which I'm not seeing in my other service

**Comment by jskeet** [comment]
Right - I suspect that may well be the problem.

I expect this has been solved by a later version of Grpc.Core - please try adding an explicit dependency to Grpc.Core version 2.34.0 or higher in your project file.

**Comment by stinkidog** [comment]
Added Grpc.Core has progressed past the point where it would break without error! Your suggestion of creating a demo console app is proving valuable as its giving much more information than the main service which is still a bit odd.

Still no success in posting to the emulator in firestore as of yet, that's for me to figure out though unless you have any direction on good resources for this?

Thank you!

**Comment by jskeet** [comment]
To connect to the emulator, you should just be able to set the EmulatorDetection property as you're already doing, and make sure that the `FIRESTORE_EMULATOR_HOST` environment variable is set.

If you know you want to connect to the emulator and never production (for now) I'd recommend using `EmulatorDetection.EmulatorOnly`. That way it will fail if the environment variable isn't set, which should make things easier to diagnose.

**Comment by stinkidog** [comment]
Thank you for your help so far - I've been trying many things again before coming back this morning but I feel I'm so close. I can push to the production firebase in the cloud successfully, but still not the emulator. This is what I'm trying to do to work with the emulator:

    public async Task PushToFirestoreEmulator(string someData)
        {

            FirestoreDb db = new FirestoreDbBuilder {
                EmulatorDetection = EmulatorDetection.EmulatorOnly,
                ProjectId = "MyProjectId" }.Build();

            CollectionReference collection = db.Collection("test-entry");
            DocumentReference document = await collection.AddAsync(new { Name = new { First = "John", Last = "Smith" }, Born = 2000 });

        }
        
Which is now producing the following error added at the bottom. I have added what I believe are all the environment variables to the container of the test console app, which are `FIRESTORE_EMULATOR_HOST=localhost:8080` and `GOOGLE_APPLICATION_CREDENTIALS={path_to_file}`. To me it just looks like the connection is not being established to the emulator but I'm at a loss as to why

> Grpc.Core.RpcException
  HResult=0x80131500
  Message=Status(StatusCode="Unavailable", Detail="failed to connect to all addresses", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1611231644.523920800","description":"Failed to pick subchannel","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":4143,"referenced_errors":[{"created":"@1611231643.960092700","description":"failed to connect to all addresses","file":"/var/local/git/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}")
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Cloud.Firestore.WriteBatch.<CommitAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Cloud.Firestore.DocumentReference.<CreateAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Google.Cloud.Firestore.CollectionReference.<AddAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestConsole.DummyService.<PushToFirestoreEmulator>d__0.MoveNext() in C:\Dev\example-dotnet-service\TestConsole\DummyService.cs:line 25
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestConsole.Program.<Main>d__0.MoveNext() in C:\Dev\example-dotnet-service\TestConsole\Program.cs:line 11

**Comment by jskeet** [comment]
If your emulator is in a different container, then I wouldn't expect `localhost:8080` to work from the client - because *its* idea of localhost will be the client container, not the emulator container.

Does that same code work if you run both the client and the emulator in the same container? (That's what I'd expect.)

I expect that to run them in separate containers, you'll need to start the emulator using the `--host-port` command line argument so that it opens a socket on an IP address that other containers can talk to. (And obviously you'll need to make sure that container port is available outside the container.)

**Comment by stinkidog** [comment]
So that entirely makes sense, but since your answer I've still had no luck getting this running. The emulator has been provided from an external source and runs via docker-compose which triggers some script to set it up. I may be able to modify that, but my gut feeling is it wont help.

I've verified that the code works, as I was able to push to the production firestore my slightly modifying to code and ignoring the emulator. I've looked and read up on networking in Docker, and was angling at the method of using the containers name in the compose file to reference the port like so:

    testconsole:
     environment:
        GOOGLE_APPLICATION_CREDENTIALS: 'path-to-my-file.json'
        FIRESTORE_EMULATOR_HOST: 'emulator:8080'
     build:
       context: .
       dockerfile: TestConsole/Dockerfile
     depends_on:
       - emulator
       
    emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile.emulator
    container_name: emulator
    environment:
      FIRESTORE_EMULATOR_HOST: "127.0.0.1:8080"
      FIREBASE_TOKEN: ${FIREBASE_TOKEN}
      FIREBASE_PROJECT: ${FIREBASE_PROJECT}
      FORCE_COLOR: 'true'
      GCLOUD_PROJECT: ${FIREBASE_PROJECT}
    ports:
      - "4000:4001"
      - "4400:4401"
      - "4600:4601"
      - "5001:5002"
      - "8080:8081"
      - "8085:8086"
      - "9000:9001"
      - "9099:9100"
      - "9229:9230" 
       
but no luck at all. It does seem there really is no one out there who has documented working with the emulator from an external docker container running .net. About all the information there is, is the following tiny snippet at the bottom of https://googleapis.dev/dotnet/Google.Cloud.Firestore/2.3.0/index.html which helpfully says *To connect to the Firestore Emulator, you need to: Connect to the emulator endpoint*. About of ideas currently

**Comment by jskeet** [comment]
I suspect this is the problem:

```text
FIRESTORE_EMULATOR_HOST: "127.0.0.1:8080"
```

My understanding - which may well be incorrect - is that that's telling the emulator to expose itself just on the loopback device, which it won't be exposed externally.

That should be easy to test: start your emulator container, and try to connect to port 8080 from outside. (Just using wget, curl or telnet should be enough to confirm whether anything's actually listening on the port.)

Note that this part is entirely separate from the client library - it's not specific to .NET at all. So you should be able to use *any* information about running the emulator in a separate container from the client. Once that's working and you can connect to it from elsewhere, I suspect the .NET code will work with no further changes.

Your point about the bottom of the documentation implies that *all* it says is "To connect to the Firestore Emulator, you need to: Connect to the emulator endpoint" - whereas it goes on to explain how to specify the emulator detection you're already using, which is all you actually need to do, once you've got the emulator exposed appropriately.

**Comment by jskeet** [comment]
Any update on this? We won't be able to help without more information, I'm afraid.
(I'll close this issue at the end of the week if there are no updates.)

**Comment by stinkidog** [comment]
It is running now yes. The steps here certainly helped, the missing pieces I believe were down to my own inexperience with Docker. 
A bridge network has been explicitly defined in the dockerfile, which hosts all the containers. We can then reference the emulators address simply via:

    environment:
      EMULATOR_HOST: "emulator:8084" 

It also turns out that there's some port mapping going on within the emulator, we the wrong port was being used for a while. Worth keeping in mind.

Thanks for the help!

**Comment by jskeet** [comment]
Great - glad it all worked out in the end :)
